# Generated by Django 5.1.4 on 2025-11-22 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(blank=True, max_length=30)),
                ('grade', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Grade must be at least 1'), django.core.validators.MaxValueValidator(10, message='Grade cannot be greater than 10')])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.studentprofile')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.subject')),
            ],
        ),
    ]
